# Generated by Django 5.2 on 2026-09-29 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountid', models.BigAutoField(db_column='accountID', primary_key=True, serialize=False)),
                ('accountnumber', models.CharField(db_column='accountNumber', max_length=50, unique=True)),
                ('accounttype', models.CharField(db_column='accountType', max_length=10)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(max_length=10)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('logid', models.BigAutoField(db_column='logID', primary_key=True, serialize=False)),
                ('entityname', models.CharField(db_column='entityName', max_length=50)),
                ('entityid', models.BigIntegerField(db_column='entityID')),
                ('action', models.CharField(max_length=50)),
                ('performedby', models.BigIntegerField(db_column='performedBy')),
                ('createdate', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'auditlog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transactionstatus',
            fields=[
                ('statusid', models.AutoField(db_column='statusID', primary_key=True, serialize=False)),
                ('statusname', models.CharField(db_column='statusName', max_length=50)),
            ],
            options={
                'db_table': 'transactionstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionid', models.BigAutoField(db_column='transactionID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transactiontype', models.CharField(db_column='transactionType', max_length=10)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
                ('fromaccountid', models.ForeignKey(db_column='fromAccountID', on_delete=django.db.models.deletion.DO_NOTHING, to='base.accounts')),
                ('toaccountid', models.ForeignKey(db_column='toAccountID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions_toaccountid_set', to='base.accounts')),
                ('statusid', models.ForeignKey(db_column='statusID', on_delete=django.db.models.deletion.DO_NOTHING, to='base.transactionstatus')),
            ],
            options={
                'db_table': 'transactions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ledgerentries',
            fields=[
                ('ledgerid', models.BigAutoField(db_column='ledgerID', primary_key=True, serialize=False)),
                ('entrytype', models.CharField(db_column='entryType', max_length=50)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
                ('accountid', models.ForeignKey(db_column='accountID', on_delete=django.db.models.deletion.DO_NOTHING, to='base.accounts')),
                ('transactionid', models.ForeignKey(db_column='transactionID', on_delete=django.db.models.deletion.DO_NOTHING, to='base.transactions')),
            ],
            options={
                'db_table': 'ledgerentries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.BigAutoField(db_column='userID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
                ('auth_user', models.OneToOneField(db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fixeddeposits',
            fields=[
                ('fdid', models.BigAutoField(db_column='fdID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interestrate', models.DecimalField(db_column='interestRate', decimal_places=2, default=5.0, max_digits=5)),
                ('durationmonths', models.IntegerField(db_column='durationMonths', default=6)),
                ('maturityamount', models.DecimalField(db_column='maturityAmount', decimal_places=2, max_digits=20)),
                ('startdate', models.DateTimeField(db_column='startDate')),
                ('maturitydate', models.DateTimeField(db_column='maturityDate')),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('accountid', models.ForeignKey(db_column='accountID', on_delete=django.db.models.deletion.DO_NOTHING, to='base.accounts')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='base.users')),
            ],
            options={
                'db_table': 'fixeddeposits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('beneficiaryid', models.BigAutoField(db_column='beneficiaryID', primary_key=True, serialize=False)),
                ('accountnumber', models.CharField(db_column='accountNumber', max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('addedtype', models.CharField(db_column='addedType', max_length=10)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='base.users')),
            ],
            options={
                'db_table': 'beneficiaries',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='userid',
            field=models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='base.users'),
        ),
    ]
