# Generated by Django 5.2 on 2026-01-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountid', models.BigAutoField(db_column='accountID', primary_key=True, serialize=False)),
                ('accountnumber', models.CharField(db_column='accountNumber', max_length=50, unique=True)),
                ('accounttype', models.CharField(db_column='accountType', max_length=10)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(max_length=10)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('logid', models.BigAutoField(db_column='logID', primary_key=True, serialize=False)),
                ('entityname', models.CharField(db_column='entityName', max_length=50)),
                ('entityid', models.BigIntegerField(db_column='entityID')),
                ('action', models.CharField(max_length=50)),
                ('performedby', models.BigIntegerField(db_column='performedBy')),
                ('createdate', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'auditlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ledgerentries',
            fields=[
                ('ledgerid', models.BigAutoField(db_column='ledgerID', primary_key=True, serialize=False)),
                ('entrytype', models.CharField(db_column='entryType', max_length=50)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'ledgerentries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionid', models.BigAutoField(db_column='transactionID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transactiontype', models.CharField(db_column='transactionType', max_length=10)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactionstatus',
            fields=[
                ('statusid', models.AutoField(db_column='statusID', primary_key=True, serialize=False)),
                ('statusname', models.CharField(db_column='statusName', max_length=50)),
            ],
            options={
                'db_table': 'transactionstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.BigAutoField(db_column='userID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
