# Generated by Django 5.2 on 2026-01-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
