# Generated by Django 5.2 on 2026-03-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_beneficiaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixeddeposits',
            fields=[
                ('fdid', models.BigAutoField(db_column='fdID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('interestrate', models.DecimalField(db_column='interestRate', decimal_places=2, default=5.0, max_digits=5)),
                ('durationmonths', models.IntegerField(db_column='durationMonths', default=6)),
                ('maturityamount', models.DecimalField(db_column='maturityAmount', decimal_places=2, max_digits=20)),
                ('startdate', models.DateTimeField(db_column='startDate')),
                ('maturitydate', models.DateTimeField(db_column='maturityDate')),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
            ],
            options={
                'db_table': 'fixeddeposits',
                'managed': False,
            },
        ),
    ]
