# Generated by Django 5.2 on 2026-03-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_users_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('beneficiaryid', models.BigAutoField(db_column='beneficiaryID', primary_key=True, serialize=False)),
                ('accountnumber', models.CharField(db_column='accountNumber', max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('addedtype', models.CharField(db_column='addedType', max_length=10)),
                ('createdate', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'beneficiaries',
                'managed': False,
            },
        ),
    ]
